---
- name: Job Roles
  hosts: ubuntu
  become: yes
  vars_files:
          "./vars/vars.yml"
  roles:
          - aptpkg
          - ssh_change_config
          - ufw_allow_ports
          - clear_journalctl_cron 
          - add_scripts_cron
          - zabbix_agent_install
