---
- name: Job Roles
  hosts: client
  become: yes
  vars_files:
          "./vars/vars.yml"
          "./vars/privvars.yml"
  roles:
          - aptpkg
          - ssh_change_config
          - ufw_allow_ports
          - clear_journalctl_cron
          - fail2ban_sshd
          - zabbix_agent_install
          - adduser_sshkey_sudoers
          - add_scripts_cron
