---
# tasks file for ufw_allow_ports
- name: Added ports in UFW Firewall
  block:
          - name: Allow everything and enable UFW
            ufw:
                    state: enabled
                    policy: allow

          - name: Set logging
            ufw:
                    logging: on

# Allow ports, ssh_tcp_port < vars/vars.yml (file global variables)                 
          - name: Allow ports
            ufw:
                    rule: allow
                    port: '{{ item }}'
                    proto: tcp
            with_items:
                    - "{{ ssh_tcp_port }}"
                    - 80
                    - 443
                    - 10113

          - name: Delete standart ssh port allowed
            ufw:
                    rule: allow
                    port: 22
                    delete: yes
# Reload ufw
          - name: Reload UFW
            ufw:
                    state: reloaded
                    policy: allow
