---
# tasks file for ufw_allow_ports
- name: Added ports in UFW Firewall
  block:
          - name: Allow everything and enable UFW
            ufw:
                    state: enabled
                    policy: allow

          - name: Set logging
            ufw:
                    logging: on

# Sometimes it is desirable to let the sender know when traffic is
# being denied, rather than simply ignoring it. In these cases, use
# reject instead of deny. In addition, log rejected connections:     
          - ufw:
                  rule: reject
                  port: auth
                  log: yes

# ufw supports connection rate limiting, which is useful for protecting
# against brute-force login attacks. ufw will deny connections if an IP
# address has attempted to initiate 6 or more connections in the last
# 30 seconds. See  http://www.debian-administration.org/articles/187
# for details. Typical usage is:
          - ufw:
                  rule: limit
                  port: ssh
                  proto: tcp

# Allow ports, ssh_tcp_port < vars/vars.yml (file global variables)                 
          - name: Allow ports
            ufw:
                    rule: allow
                    port: '{{ item }}'
                    proto: tcp
            with_items:
                    - "{{ ssh_tcp_port }}"
                    - 37903
                    - 80
                    - 443
                    - 10113

# Reload ufw
          - name: Reload UFW
            ufw:
                    state: reloaded
                    policy: allow
