---
# tasks file for zabbix-agent_install

- name: showpkg zabbix-agent
  command: "apt-cache showpkg zabbix-agent"
  register: showpkg_result

- name: Debug registered var
  debug: var=showpkg_result.stdout_lines

- name: Checking for a deb file
  stat:
          path: "{{ zabbix_agent_install_file_deb }}"
  register: deb_file

- name: Deleting a deb file if it exists
  file:
          path: "{{ zabbix_agent_install_file_deb }}"
          state: absent
  when: deb_file.stat.exists

- name: Deb file download
  get_url:
          url: "{{ zabbix_agent_install_url_deb }}"
          dest: "{{ zabbix_agent_install_file_deb }}"

- name: dpkg -i "{{ zabbix_agent_install_file_deb }}"
  apt:
          deb: "{{ zabbix_agent_install_file_deb }}"

- name: Update apt-get repo
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install PKG, '{{ zabbix_agent_install_agent }}'
  apt:
          name: '{{ zabbix_agent_install_agent }}'
          state: present
